feat: assessment forms in new format (#21)
nuecho/covidflow pull request #36
Opened 2020-09-16 14:18 UTC by NetBKarine

## Description

Changed tested positive and check-in return forms to use the new assessment form and self-isolation form (basic/generic assessment form was already changed).
This necessitated the addition of an "assessment_type" slot based on the assessment form's trigger intent (with a little bit of gymnastics for tested_positive, because the self-isolation form happens between the intent and the assessment form. "deny" can be mapped to "tested_positive", but "affirm" can be a valid trigger intent for a generic assessment, so validation is necessary if "affirm" is answered in self-isolation). 
For this slot I bumped into a bug with the tracker.form_slots_to_validate helper (or problem that is not a bug... Anyway. Core and the SDK are not coherent), so I had to recreate the equivalent in form_helper.

## Related issues

closes #21

## Checklist

- [X] PR title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) guidelines 
- [X] All relevant PR sections are populated, irrelevant ones are removed

2020-09-16 14:24 UTC, NetBKarine commented on core/data/rules.yml
> +      - action: utter_self_isolation_final
I know this is a lot of messages but I wasn`t sure on how to regroup them so I left them like this for now.

2020-09-16 18:29 UTC, mbrisebo-perso requested changes

2020-09-16 18:29 UTC, mbrisebo-perso commented on action-server/covidflow/actions/assessment_form.py
> +        return [SlotSet(ASSESSMENT_TYPE_SLOT, AssessmentType.TESTED_POSITIVE)]
Hum...
(En espérant comprendre le code)
Est-on si sûr qu'à partir du moment où l'usager s'est déclaré positif, il n'y aura qu'un seul et unique formulaire en jeu?

2020-09-16 19:47 UTC, NetBKarine commented on action-server/covidflow/actions/assessment_form.py
> +        return [SlotSet(ASSESSMENT_TYPE_SLOT, AssessmentType.TESTED_POSITIVE)]
C'est plutôt qu'on est sûrs que si on a eu l'intention "tested_positive" et qu'elle n'a pas été "effacée" par la gestion d'erreur, on est entrés dans le tested_positive form. Et comme on peut pas faire deux assessments, on ne devrait pas avoir de situation problématique. Mais puisqu'on n'a besoin de faire le changement que dans un cas très précis, je pense que je vais préciser la condition quand même, au cas où.

2020-09-17 15:46 UTC, mbrisebo-perso approved these changes

2020-09-17 16:06 UTC, merged