feat: new daily ci enroll form (#29)
nuecho/covidflow pull request #41
Opened 2020-09-24 13:04 UTC by NetBKarine

## Description

Got the "do you want to enroll" question out of the form. For this and the "digressions" when collecting the phone number, I had to isolate the daily check-in enrollment rules, and did it with an action that does nothing, to be used as a marker to come back to the correct form. It works well, like a checkpoint but with more flexibility.

Other things that look like digressions I had to leave in the form even though the plan was to get them out, because it is cleaner this way when the "digression" affects how we set a slot or how we ask for it. We can't ask the question inside a digression rule and automatically come back to the form using the user's answer, as I had thought would be possible.

Also, added a `make clean` task. The description was there, but not the task itself.

## Related issues

closes #29

## Checklist

- [X] PR title follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary) guidelines 
- [X] All relevant PR sections are populated, irrelevant ones are removed

2020-09-24 19:55 UTC, NetBKarine commented on core/config/config.en.yml
> +  #   case_sensitive: false
Y'a un issue avec le modèle pour le ConveRT, je vais ajouter un commentaire avec l'issue, j'ai oublié. En attendant que ce soit à jour dans rasa 2 ET qu'on update, on va laisser ça de même.

2020-09-25 15:18 UTC, mbrisebo-perso requested changes
À part un commentaire sur un bout de code suspect, LG(reat)TM

2020-09-28 13:34 UTC, mbrisebo-perso approved these changes

2020-09-28 13:34 UTC, mbrisebo-perso commented on action-server/covidflow/actions/daily_ci_enroll_form.py
> +        )
OK, je comprends mieux...
C'est une syntaxe propre à Python que je n'avais pas encore rencontrée.

2020-09-28 13:41 UTC, NetBKarine commented on action-server/covidflow/actions/daily_ci_enroll_form.py
> +        )
Oui, c'est le "shorthand if" de python. Assez utile, un peu bizarre, comme à peu près tout en python.

2020-09-28 13:41 UTC, merged